### PR TITLE
upgrade packages

### PR DESCRIPTION
**Pull request by simenstoa**
Upgrade dotnet packages from 5 to 6. This made `Program` stop running with dotnet core 2.1, so i guess this is a breaking change?

### CODE REVIEW

**Comment by simenstoa** [comment]
Ref https://github.com/digipost/signature-api-client-dotnet/issues/365

**Comment by runeflobakk** [comment]
As someone who is not versed with .NET, should it be OK to bump the required dotnet core version? What will be the new minimum version? Is the upgrade trivial for any existing integrations still on dotnet core 2.1, if any? 
If there is a known vulnerability in v5 of those packages, and Microsoft does not have any intention of fixing them, I guess they should be considered dead anyway, so bumping the minimum version of Core seems necessary. And I guess that mandates a new major version.

**Comment by simenstoa** [comment]
Dotnet core 2.1 had end of life in August 2021, so it's no longer supported by Microsoft either: https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

So I think it's ok that we release a new major version that does not support it.

**Comment by hanskhe** [comment]
We should be able to drop support for Dotnet Core 2.1 without issue. As pointed out, it is no longer in support. 

I agree with Rune, this would mandate a new major version release.

**Review by hanskhe — APPROVED** [review]

**Pull request merged**
